import { Inter } from "next/font/google";
import "./globals.css";
import HorizontalBar from "@/components/NavBar/HorizontalBar";
import VerticalBar from "@/components/NavBar/VerticalBar";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className} >
      
        <main className='wrapper'>
          <div className="main-canvas">
            <div className="h-bar">
                  <HorizontalBar/>
            </div>
            <div className="v-bar">
                  <VerticalBar/>
            </div>
            <div className="wind-main">
                {children}
            </div>
          </div>

        </main>
         
      </body>
    </html>
  );
}
